name: Smoke Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Run Tests
      run: mvn test

    - name: Slack Notification
      uses: slackapi/slack-github-action@v1.18.0
      with:
        status: ${{ job.status }}
        channel: '#team-ais-automation_builds'
      if: failure()
