name: Smoke Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        - with:
            - cache: maven
      - name: Run Tests
        run: mvn test -Dtest=SampleTest