name: Smoke Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '17'
        cache: 'maven'
    - name: Run Tests
      run: mvn test -Dtest=SampleTest